### ISSUE TITLE
Validate your Project Idea

### ISSUE THREAD

**Issue by santiagobasulto** [rmotr-career-services/career-services-eggarcia28#1]
Now that you've chosen your project idea, it's time to make sure it's feasible before you commit to it.

Things to check:

- If you are using API's, try each one out and make sure the information you are getting is what you expect. Sometimes you have to request an API key to get access.
- If you are using third party libraries, check out the documentation/try them out and make sure they work as you expect.
- Does your project idea have any legal considerations?
- Do you think you can realistically develop your project in two weeks?

**Deliverable**: Write the research you did to validate your project idea and your findings from it below in a comment and then close the issue.

`RMOTR: DD#3`

**Comment by eggarcia28** [comment]
I'm using data that was made publicly available by the MLS Player's Union. it is used here: https://mlsplayers.org/resources/salary-guide

And the cleaned data set including roster designations here: https://worville.github.io/jekyll/update/2018/05/13/Cleaning-The-MLS-Salary-Dump.html

The main libraries I will use are pandas, matplotlib, and possibly seaborn. It should be possible for me to develop everything quickly. 

Since the data I used was pretty clean, it was easy to start the project. However, I do have concerns that my current scope may be too small. It may be a difficult task to to widen that scope and find that same roster designation data for previous years.
