### ISSUE TITLE
Pick a project idea

### ISSUE THREAD

**Issue by santiagobasulto** [rmotr-career-services/career-services-eggarcia28#7]
It is recommended that you come up with at least 3 ideas for your project and then choose the one you like the best and seems the most technically feasible.

**Deliverable**: Once you have selected your project idea, write the idea and why you chose it in this issue and close it for review.

`RMOTR: DD#2`

**Comment by eggarcia28** [comment]
The idea I have is to look at the recently released salary data from Major League Soccer and use it to find if spending money a certain way leads to a team's success. I chose it because it is very recent data and appeals to me because my team, the Chicago Fire, does not seem to know what it is doing with its money. If I can look at what successful teams are doing right, then I will finally understand what my team is doing wrong.
